# Generated by Django 5.0.1 on 2024-02-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RichMans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('money', models.PositiveBigIntegerField()),
                ('country', models.CharField(max_length=80)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='richmans.gender')),
            ],
        ),
    ]
